# my_carparts_detector/configs/train_carparts_job.yaml
defaults:
  - model: v9-t       # From installed yolo package (e.g., yolo/config/model/v9-c.yaml)
  - task: inference # From installed yolo package (e.g., yolo/config/task/train.yaml)
  - dataset: carparts-bb # YOUR custom dataset config (configs/dataset/carparts-bb.yaml)
  - general           # From installed yolo package (e.g., yolo/config/general.yaml)

# Your project-specific settings or overrides for this job
name: carparts_${model.name}_01 # Name of the training run

data:
  data/carparts-bb/test

out_path:
  outputs

task:
  epoch: 0

hydra:
  searchpath:
    - file:///Users/huubal/ScanGo/reykjavik_orientation/YOLO/yolo/config
  run:
    # Output directory relative to the location of this config file OR hydra.cwd
    # If running `python scripts/train.py` from project root, hydra.cwd is project root.
    # So, this path will be project_root/outputs/runs/carparts_yolov9c_run_01
    dir: outputs/runs/${name}
  job:
    # When using @hydra.main(config_path="../configs", ...)
    # the config_path becomes the primary search path for this job file.
    # We will augment the search path when running the script to find yolo pkg configs.
    name: ${name} # Job name for Hydra logging
